from __future__ import annotations

import pickle
from hashlib import sha256
from pathlib import Path

MODEL_DIR = Path(__file__).resolve().parent
METRICS_PATH = MODEL_DIR / "metrics.pkl"


def _load_metrics_table() -> dict[str, dict[str, dict[str, float | int | bool]]]:
    if not METRICS_PATH.exists():
        return {}

    with METRICS_PATH.open("rb") as file:
        table = pickle.load(file)

    if not isinstance(table, dict):
        raise ValueError("metrics.pkl must contain dict[state_key][pitch_code] = metrics")

    return table


METRICS_TABLE = _load_metrics_table()


def _stable_unit_interval(key: str) -> float:
    digest = sha256(key.encode("utf-8")).hexdigest()
    return int(digest[:8], 16) / 0xFFFFFFFF


def _fallback_pitch_metrics(state_key: str, pitch: str, q_value: float) -> dict[str, float | int | bool]:
    """Deterministic fallback used only before Statcast metrics are exported.

    Real app metrics come from metrics.pkl, generated by train_and_export_q_table.py.
    """
    seed = _stable_unit_interval(f"{state_key}:{pitch}")
    whiff_rate = min(0.62, max(0.08, 0.22 + seed * 0.28 + q_value * 0.8))
    baa = min(0.34, max(0.08, 0.265 - seed * 0.08 - q_value * 0.9))
    mlb_frequency = min(0.72, max(0.04, 0.11 + seed * 0.48))
    sample_size = int(240 + seed * 5200)

    return {
        "expected_delta_run_exp": round(-q_value, 3),
        "sample_size": sample_size,
        "whiff_rate": round(whiff_rate, 3),
        "baa": round(baa, 3),
        "mlb_frequency": round(mlb_frequency, 3),
        "low_sample_warning": sample_size < 500,
    }


def get_pitch_metrics(state_key: str, pitch: str, q_value: float) -> dict[str, float | int | bool]:
    state_metrics = METRICS_TABLE.get(state_key)
    if state_metrics and pitch in state_metrics:
        metrics = dict(state_metrics[pitch])
        metrics["expected_delta_run_exp"] = round(-q_value, 3)
        metrics["metrics_source"] = "statcast"
        return metrics

    metrics = _fallback_pitch_metrics(state_key, pitch, q_value)
    metrics["metrics_source"] = "deterministic_fallback"
    return metrics
